---
- name: Login into registries
  become: true
  docker_login:
    registry: '{{ item.registry }}'
    username: '{{ item.username }}'
    password: '{{ item.password }}'
  loop: '{{ docker_registries }}'
  no_log: true
  tags: [ d1A, d1B, d1C, d2A, d2B, d2C ]

- name: create directory with parent directories
  file:
    path: /root/challenges
    state: directory
  become: true
  tags: [ d1A, d1B, d1C, d2A, d2B, d2C ]

- name: copy docker-compose.yml
  become: true
  copy:
    src: files/docker-compose.yml
    dest: /root/challenges/docker-compose.yml
  tags: [ d1A, d1B, d1C, d2A, d2B, d2C ]

- name: Compose down --rmi all
  shell: docker compose down --rmi all || echo \"probably new compose\"
  become: true
  args:
    chdir: /root/challenges
  tags: [ d1A, d1B, d1C, d2A, d2B, d2C ]

- name: Delete non compose containers
  shell: docker rm -f $(docker ps -a -q) || echo \"no container\"
  become: true
  tags: [ d1A, d1B, d1C, d2A, d2B, d2C ]

- name: Delete volumes
  shell: docker volume rm $(docker volume ls -q) || echo \"volumes\"
  become: true
  tags: [ d1A, d1B, d1C, d2A, d2B, d2C ]
  
- name: Delete images
  shell: docker rmi -f $(docker images -a -q) || echo \"no images\"
  become: true
  tags: [ d1A, d1B, d1C, d2A, d2B, d2C ]

- name: Remove docker compose
  ansible.builtin.file:
    path: /root/challenges/docker-compose.yml
    state: absent
  tags: [ d1A, d1B, d1C, d2A, d2B, d2C ]

- name: copy docker-compose.yml d1A
  become: true
  copy:
    src: files/docker-compose-d1A.yml
    dest: /root/challenges/docker-compose.yml
  tags:
    - d1A

- name: copy docker-compose.yml d1B
  become: true
  copy:
    src: files/docker-compose-d1B.yml
    dest: /root/challenges/docker-compose.yml
  tags:
    - d1B

- name: copy docker-compose.yml d1C
  become: true
  copy:
    src: files/docker-compose-d1C.yml
    dest: /root/challenges/docker-compose.yml
  tags:
    - d1C

- name: copy docker-compose.yml d2A
  become: true
  copy:
    src: files/docker-compose-d2A.yml
    dest: /root/challenges/docker-compose.yml
  tags:
    - d2A

- name: copy docker-compose.yml d2B
  become: true
  copy:
    src: files/docker-compose-d2B.yml
    dest: /root/challenges/docker-compose.yml
  tags:
    - d2B

- name: copy docker-compose.yml d2C
  become: true
  copy:
    src: files/docker-compose-d2C.yml
    dest: /root/challenges/docker-compose.yml
  tags:
    - d2C

- name: Compose up
  shell: docker compose up -d
  become: true
  args:
    chdir: /root/challenges
  tags: [ d1A, d1B, d1C, d2A, d2B, d2C ]

- name: docker output
  shell: docker ps -a
  become: true
  tags: [ d1A, d1B, d1C, d2A, d2B, d2C ]
