apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: https://nginx-auth:9090
    isDefault: true
    basicAuth: true
    tlsSkipVerify: true
    basicAuthUser: admin
    basicAuthPassword: admin

