version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./Prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./Certs/ClientCerts:/certs
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    volumes:
      - ./Grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "3000:3000"
    networks:
      - monitoring
    depends_on:
      - prometheus

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    command:
      - '--path.rootfs=/host'
    pid: host
    volumes:
      - /:/host:ro,rslave
    ports:
      - "9090:9090"
    networks:
      - monitoring

  exporter_exporter:
    image: prometheus-community/exporter_exporter
    ports:
      - "9100:9100"
    volumes:
      - ./Certs/ServerCerts:/certs
    command:
      - --web.listen-address=:9100
      - --config.file=/exporter_exporter.yml
      - --tls.server-cert=/Certs/ServerCerts/server-cert.pem
      - --tls.server-key=/Certs/ServerCerts/server-key.pem
      - --tls.client-ca=/Certs/ServerCerts/ca-cert.pem
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge