version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./Prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    volumes:
      - ./Grafana/provisioning:/etc/grafana/provisioning
    networks:
      - monitoring
    depends_on:
      - prometheus

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    command:
      - '--path.rootfs=/host'
    pid: host
    volumes:
      - /:/host:ro,rslave
    networks:
      - monitoring

  nginx-auth:
    image: nginx:alpine
    container_name: nginx-node-exporter
    restart: unless-stopped
    ports:
      - "9100:9100"
      - "9090:9090"
      - "443:3000"
    volumes:
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./Nginx/.htpasswd:/etc/nginx/.htpasswd:ro
      - ./Nginx/certs:/etc/nginx/certs:ro
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge