global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node-exporter"
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ["nginx-auth:9100"]
        labels:
          instance: "Ubi"