global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node-exporter"
    scheme: https
    metrics_path: /metrics
    tls_config:
      ca_file: /certs/ca-cert.pem
      cert_file: /certs/client-cert.pem 
      key_file: /certs/client-key.pem
      insecure_skip_verify: false
    static_configs:
      - targets: ["exporter_exporter:9100"]
        labels:
          instance: "Ubi"