global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node-exporter"
    basic_auth:  # Add credentials
      username: admin
      password: admin
    static_configs:
      - targets: ["nginx-auth:9100"]
        labels:
          instance: "Ubi"